### ISSUE TITLE
Peer to Peer Review - 15/01/2020

### ISSUE THREAD

**Issue by SofiBretz** [thsvr/spy-book#10]
## Bugs
No bugs were found :)

## Enhancements
1. On /app/controllers/posts_controller.rb:
- In the Index method, please check for the status on 'friends'.
2. On /app/controllers/likes_controller.rb:
- Line 39, please check if it is not 'nill' before destroy. 
3. On /app/controllers/likes_controller.rb:
- Line 10, please check if 'post' exist. 
4. On /app/controllers/likes_controller.rb:
- In line 22, please check if the 'id' already exists. 
5. On /app/models/friendship.rb:
- Check if the 'belongs_to' works well, because both are pointing to the 'user', maybe this can cause a crash also.

## Further Comments
Good job team! ;)
> Reviewed with :heart: by Team 35: The Deadpools

**Comment by Aaron-RN** [comment]
Good pointers , will look into them.

Thanks for the review
